# Generated by Django 6.0.4 on 2026-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("nl", "Nederlands"),
                    ("en", "English"),
                    ("it", "Italiano"),
                    ("es", "Español"),
                ],
                default="fr",
                max_length=2,
                verbose_name="language",
            ),
        ),
    ]
