# Generated by Django 6.0.4 on 2026-05-05 07:09

from django.db import migrations, models


def _bump_renaud(apps, schema_editor):
    """Renaud is the project owner — give him head-room so he can keep
    creating teams in dev/staging without being blocked by his own quota
    feature. New deployments without a `renaud` user are no-ops."""
    User = apps.get_model("customuser", "CustomUser")
    User.objects.filter(username="renaud").update(team_quota=10)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0003_normalize_legacy_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="team_quota",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of active teams this user can own. Defaults to 0 — creating a team is a paid feature; admins bump this per user (or via a future billing flow).",
            ),
        ),
        migrations.RunPython(_bump_renaud, _noop_reverse),
    ]
