# Generated by Django 6.0.4 on 2026-04-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_update_default_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_foo_admin',
        ),
    ]
