# Generated by Django 2.2.13 on 2020-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('event', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='events',
            field=models.ManyToManyField(blank=True, to='event.Event'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='members',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
    ]
