# Generated by Django 4.2.1 on 2023-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('agenda', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='events',
            field=models.ManyToManyField(blank=True, to='event.event'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='members',
            field=models.ManyToManyField(blank=True, to='member.member'),
        ),
    ]
