# Generated by Django 6.0.5 on 2026-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200821_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
