# Generated by Django 6.0.4 on 2026-04-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_id'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='team.team'),
        ),
    ]
