# Generated by Django 6.0.4 on 2026-04-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_team'),
        ('team', '0002_bootstrap_default_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='team.team'),
        ),
    ]
