# Generated by Django 6.0.4 on 2026-04-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_team_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="athlete_can_read_notes",
            field=models.BooleanField(
                default=False,
                help_text="If True, athletes can read their own coach notes. Default False (notes are coach-only).",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="chat_mode",
            field=models.CharField(
                choices=[
                    ("all", "All members can post"),
                    ("coaches_only", "Only coaches can post"),
                ],
                default="all",
                help_text="Defines who can post messages in the team chat.",
                max_length=20,
            ),
        ),
    ]
