# Generated by Django 6.0.4 on 2026-04-29 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_member_created_at_member_updated_at"),
        ("team", "0003_add_chat_and_notes_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this athlete joined the team.",
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this athlete left the team. NULL = currently active.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="member.member",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="team.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(fields=["team", "left_at"], name="membership_team_left_idx"),
                    models.Index(fields=["member", "left_at"], name="membership_member_left_idx"),
                ],
            },
        ),
    ]
