# Generated by Django 6.0.4 on 2026-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_add_label_translations"),
        ("team", "0005_migrate_member_teams_to_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="attendance_statuses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Statuses available for marking attendance in this team's events. Default: present, absent, excused.",
                related_name="teams",
                to="attendance.attendancestatus",
            ),
        ),
    ]
