# Generated by Django 6.0.4 on 2026-05-05 05:53

from django.db import migrations, models


def _opt_out_existing_teams_from_notify(apps, schema_editor):
    """Existing teams predate this feature: opt them out of email notifications
    by default to avoid spamming managers right after deployment. New teams
    keep the model default (notify=True). A trainer can re-enable per team
    via the admin or a PATCH /teams/{id}/."""
    Team = apps.get_model("team", "Team")
    Team.objects.update(notify_managers_on_join_request=False)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_link_existing_teams_to_default_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="join_request_policy",
            field=models.CharField(
                choices=[
                    ("manual", "Manual — managers accept/reject each request"),
                    ("auto", "Auto-accept — every join request is accepted immediately"),
                ],
                default="manual",
                help_text="Manual = managers accept/reject each TeamJoinRequest. Auto = every join request is accepted immediately on submission.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="notify_managers_on_join_request",
            field=models.BooleanField(
                default=True,
                help_text="When join_request_policy=manual, send the owner and managers an email with accept/reject magic links on each new request. Ignored when policy=auto (no manual decision is needed).",
            ),
        ),
        migrations.RunPython(_opt_out_existing_teams_from_notify, _noop_reverse),
    ]
