# Generated by Django 6.0.4 on 2026-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='ai_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='ai_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='frequency_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
