# Generated by Django 6.0.4 on 2026-04-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0003_program_created_at_program_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="members",
        ),
    ]
