# Generated by Django 6.0.4 on 2026-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0004_remove_members_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
