# Generated by Django 6.0.4 on 2026-05-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0005_add_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["-updated_at", "-id"], "verbose_name": "Program"},
        ),
    ]
