# Generated by Django 6.0.4 on 2026-05-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0007_backfill_refer_program_from_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="events",
        ),
    ]
