# Generated by Django 6.0.4 on 2026-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0006_add_is_active"),
        ("sport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="energy_systems",
            field=models.ManyToManyField(
                blank=True, related_name="sports", to="exercise.energysystem"
            ),
        ),
    ]
