# Generated by Django 6.0.4 on 2026-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sport", "0003_link_natation_to_energysystems"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="name_fr",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="name_it",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="name_nl",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
