# Generated by Django 6.0.4 on 2026-04-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0003_add_chat_and_notes_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Rich HTML content (sanitized via bleach on save)."),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the message is edited after creation.",
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp. Non-null = deleted.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Author of the message. SET_NULL on user deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="team.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "deleted_at", "-created_at"],
                        name="msg_team_deleted_created_idx",
                    )
                ],
            },
        ),
    ]
