# Generated by Django 6.0.4 on 2026-04-27 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phonenumber')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('teams', models.ManyToManyField(blank=True, related_name='members', to='team.team')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
            },
        ),
    ]
