# Generated by Django 4.2.1 on 2023-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phonenumber')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Member',
            },
        ),
    ]
