# Generated by Django 2.2.13 on 2020-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
            ],
            options={
                'verbose_name': 'Member',
            },
        ),
    ]
