# Generated by Django 2.2.13 on 2020-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='member',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phonenumber'),
        ),
    ]
