# Generated by Django 6.0.4 on 2026-04-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_member_created_at_member_updated_at"),
        ("team", "0005_migrate_member_teams_to_membership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="teams",
        ),
    ]
