# Generated by Django 6.0.4 on 2026-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0004_remove_teams_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
        ),
    ]
