# Generated by Django 4.2.1 on 2023-05-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('goal', models.CharField(blank=True, max_length=100, null=True, verbose_name='goal')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='color')),
                ('date', models.DateField(blank=True, null=True)),
                ('hour_start', models.TimeField(blank=True, null=True)),
                ('hour_end', models.TimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, to='member.member')),
                ('refer_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_agenda', to='agenda.agenda', verbose_name='refer_agenda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
