# Generated by Django 6.0.4 on 2026-04-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('member', '0002_initial'),
        ('program', '0001_initial'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, to='member.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='refer_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_program', to='program.program', verbose_name='refer_program'),
        ),
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='round.round'),
        ),
    ]
