# Generated by Django 4.2.1 on 2023-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('round', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='round.round'),
        ),
    ]
