# Generated by Django 2.2.13 on 2020-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='round.Round'),
        ),
    ]
