# Generated by Django 6.0.4 on 2026-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ai_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ai_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="ai_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="generated_by_ai",
            field=models.BooleanField(default=False),
        ),
    ]
