# Generated by Django 6.0.4 on 2026-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_initial'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='round.round'),
        ),
    ]
