# Generated by Django 6.0.4 on 2026-05-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_event_created_at_event_updated_at"),
        ("program", "0008_remove_program_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="refer_program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="program.program",
                verbose_name="refer_program",
            ),
        ),
    ]
