# Generated by Django 2.2.13 on 2020-08-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.CharField(max_length=10, verbose_name='abv')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('t_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='start')),
                ('t_break', models.CharField(blank=True, max_length=10, null=True, verbose_name='break')),
                ('repetition', models.PositiveIntegerField(default=1, verbose_name='repetition')),
                ('distance', models.PositiveIntegerField(default=100, verbose_name='distance')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notes')),
                ('energysegment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.EnergySegment', verbose_name='Energy Segment')),
            ],
            options={
                'verbose_name': 'Exercise',
            },
        ),
    ]
