# Generated by Django 4.2.1 on 2023-05-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='refer_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_round', to='round.round', verbose_name='refer_round'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.stroke', verbose_name='stroke'),
        ),
        migrations.AddField(
            model_name='energysegment',
            name='energysystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.energysystem'),
        ),
    ]
