# Generated by Django 6.0.4 on 2026-04-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='refer_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_round', to='round.round', verbose_name='refer_round'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.stroke', verbose_name='stroke'),
        ),
    ]
