# Generated by Django 6.0.4 on 2026-04-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='refer_round',
        ),
    ]
