# Generated by Django 2.2.13 on 2020-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20200821_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
        ),
    ]
