# Generated by Django 6.0.4 on 2026-04-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0002_exercise_created_at_exercise_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "Français"),
                    ("nl", "Nederlands"),
                    ("en", "English"),
                    ("it", "Italiano"),
                    ("es", "Español"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
