# Generated by Django 6.0.5 on 2026-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_energysegment_id_alter_energysystem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(db_index=True, default=1, verbose_name='order'),
        ),
    ]
