# Generated by Django 6.0.4 on 2026-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0005_alter_exercise_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="energysegment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="energysystem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modality",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
