# Generated by Django 6.0.4 on 2026-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0006_add_is_active"),
        ("sport", "0004_sport_name_en_sport_name_es_sport_name_fr_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="modality",
            unique_together={("name", "sport")},
        ),
        migrations.AddField(
            model_name="energysegment",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="energysegment",
            name="description_es",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="energysegment",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="energysegment",
            name="description_it",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="energysegment",
            name="description_nl",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="energysystem",
            name="name_en",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="energysystem",
            name="name_es",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="energysystem",
            name="name_fr",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="energysystem",
            name="name_it",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="energysystem",
            name="name_nl",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="modality",
            name="name_en",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="modality",
            name="name_es",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="modality",
            name="name_fr",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="modality",
            name="name_it",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="modality",
            name="name_nl",
            field=models.CharField(max_length=20, null=True, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="modality",
            unique_together={
                ("name", "sport"),
                ("name_en", "sport"),
                ("name_es", "sport"),
                ("name_fr", "sport"),
                ("name_it", "sport"),
                ("name_nl", "sport"),
            },
        ),
    ]
