# Generated by Django 6.0.4 on 2026-04-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_initial'),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('count', models.PositiveIntegerField(default=1)),
                ('t_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='start')),
                ('t_break', models.CharField(blank=True, max_length=10, null=True, verbose_name='break')),
                ('exercises', models.ManyToManyField(blank=True, to='exercise.exercise')),
                ('refer_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_event', to='event.event', verbose_name='refer_event')),
            ],
            options={
                'verbose_name': 'Round',
            },
        ),
    ]
