# Generated by Django 2.2.13 on 2020-08-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('t_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='start')),
                ('t_break', models.CharField(blank=True, max_length=10, null=True, verbose_name='break')),
                ('exercises', models.ManyToManyField(blank=True, to='exercise.Exercise')),
                ('refer_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_event', to='event.Event', verbose_name='refer_event')),
            ],
            options={
                'verbose_name': 'Round',
            },
        ),
    ]
