# Generated by Django 6.0.4 on 2026-04-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='refer_event',
        ),
    ]
