# Generated by Django 3.1 on 2020-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
