# Generated by Django 6.0.4 on 2026-04-27 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round", "0002_round_created_at_round_updated_at"),
        ("sport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rounds",
                to="sport.sport",
            ),
        ),
    ]
