# Generated by Django 6.0.5 on 2026-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_alter_round_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
