# Generated by Django 6.0.4 on 2026-04-27 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round", "0004_set_sport_from_exercises"),
        ("sport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="rounds", to="sport.sport"
            ),
        ),
    ]
