# Generated by Django 6.0.4 on 2026-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round", "0007_set_default_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("nl", "Nederlands"),
                    ("en", "English"),
                    ("it", "Italiano"),
                    ("es", "Español"),
                ],
                max_length=2,
            ),
        ),
    ]
