# Generated by Django 6.0.4 on 2026-05-06 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round", "0008_alter_round_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="t_break",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="time_mmss_invalid",
                        message="Expected format: MM:SS (e.g. 1:30).",
                        regex="^\\d{1,3}:[0-5]\\d$",
                    )
                ],
                verbose_name="break",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="t_start",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="time_mmss_invalid",
                        message="Expected format: MM:SS (e.g. 1:30).",
                        regex="^\\d{1,3}:[0-5]\\d$",
                    )
                ],
                verbose_name="start",
            ),
        ),
    ]
