# Generated by Django 6.0.4 on 2026-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancestatus",
            name="label_en",
            field=models.CharField(
                help_text="Display label, translated via modeltranslation.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancestatus",
            name="label_es",
            field=models.CharField(
                help_text="Display label, translated via modeltranslation.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancestatus",
            name="label_fr",
            field=models.CharField(
                help_text="Display label, translated via modeltranslation.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancestatus",
            name="label_it",
            field=models.CharField(
                help_text="Display label, translated via modeltranslation.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancestatus",
            name="label_nl",
            field=models.CharField(
                help_text="Display label, translated via modeltranslation.",
                max_length=100,
                null=True,
            ),
        ),
    ]
