# Generated by Django 6.0.4 on 2026-04-28 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0002_team_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("ping", "Ping"),
                            ("plan", "Generate plan"),
                            ("training", "Generate training"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="Anthropic model identifier (e.g. claude-haiku-4-5)",
                        max_length=100,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_creation_tokens", models.IntegerField(default=0)),
                ("cache_read_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to="team.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "-created_at"], name="aiusage_aiu_team_id_fcdcd9_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="aiusage_aiu_user_id_50fd3e_idx"
                    ),
                    models.Index(fields=["-created_at"], name="aiusage_aiu_created_71aaac_idx"),
                ],
            },
        ),
    ]
